# Number of days of inactivity before an issue becomes stale
daysUntilStale: 120
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - keep
  - enhancement
  - confirmed
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Hey! This issue has been open for quite some time without any new comments now.
  It will be closed automatically in a week if no further activity occurs.
  
  Thank you for using WLED!
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
