language: python
os: linux
python:
  - '3.7'

env:
    - PLATFORMIO_CI_SRC=wled00

install:
  - pip install -U platformio
  - platformio upgrade --dev

script:
    # - platformio ci --project-conf=./platformio.ini
    - platformio run