#pragma once

#include <BLEUtils.h>

#ifdef BLE_WLED_DEBUG
#define BLE_DEBUG_PRINT(x) DEBUGOUT.print(x)
#define BLE_DEBUG_PRINTLN(x) DEBUGOUT.println(x)
#define BLE_DEBUG_PRINTF(x...) DEBUGOUT.printf(x)
#else
#define BLE_DEBUG_PRINT(x)
#define BLE_DEBUG_PRINTLN(x)
#define BLE_DEBUG_PRINTF(x...)
#endif

#define WLED_BLE_2_JSON_NAME "WLED BLE2JSON"
#define WLED_BLE_SERVICE_ID "bee3d55e-a2eb-4f7a-889b-13192c8c1819"

#define WLED_BLE_MAIN_SERVICE_ID 0x0000
#define WLED_BLE_MAIN_BLE_ON_ID 0x0001

#define WLED_BLE_DATA_SERVICE_ID 0x0100
#define WLED_BLE_STATE_INFO_DATA_ID 0x0101
#define WLED_BLE_STATE_INFO_CONTROL_ID 0x0102
#define WLED_BLE_STATE_NOTIFY_ID 0x103

#define WLED_BLE_PALETTE_NAME_SERVICE_ID 0x200
#define WLED_BLE_PALETTE_NAME_DATA_ID 0x201
#define WLED_BLE_PALETTE_NAME_CONTROL_ID 0x202

#define WLED_BLE_FX_DETAILS_SERVICE_ID 0x300
#define WLED_BLE_FX_DETAILS_DATA_ID 0x301
#define WLED_BLE_FX_DETAILS_CONTROL_ID 0x302

#define WLED_BLE_FX_NAMES_SERVICE_ID 0x400
#define WLED_BLE_FX_NAMES_DATA_ID 0x401
#define WLED_BLE_FX_NAMES_CONTROL_ID 0x402

#define WLED_BLE_PRESETS_SERVICE_ID 0x500
#define WLED_BLE_PRESETS_DATA_ID 0x501
#define WLED_BLE_PRESETS_CONTROL_ID 0x502

#define WLED_BLE_PALETTE_DETAILS_SERVICE_ID 0x600
#define WLED_BLE_PALETTE_DETAILS_DATA_ID 0x601
#define WLED_BLE_PALETTE_DETAILS_CONTROL_ID 0x602

#define BLE_UUID(id) createId(WLED_BLE_SERVICE_ID, id)

BLEUUID createId(std::string value, uint16_t id)
{
  BLEUUID bleUuid = BLEUUID(value);
  esp_bt_uuid_t *baseUuid = bleUuid.getNative();

  memcpy(&baseUuid->uuid.uuid128[12], &id, sizeof(id));

  return bleUuid;
}
