name: WLED Release CI

on:
  push:
    tags:
      - '*'

jobs:
  
  wled_build:
    uses: ./.github/workflows/build.yml
    
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: wled_build
    steps:
    - uses: actions/download-artifact@v4
      with:
        merge-multiple: true
    - name: Create draft release
      uses: softprops/action-gh-release@v1
      with:
        draft: True
        files: |
          *.bin
          *.bin.gz

