name: 'Toxicity check'
on: 
  issue_comment:
    types: ['created', 'edited', 'deleted']
  pull_request_review:
  pull_request_review_comment:
  issues:
    types: ['opened', 'edited', 'deleted', 'closed', 'reopened', 'locked', 'unlocked']
  pull_request:
    types: ['opened', 'edited', 'closed', 'reopened', 'locked', 'unlocked']

jobs:
  toxicity-check-job:
    runs-on: ubuntu-latest
    name: Toxicity check job
    steps:
      - name: Toxicity check
        uses: TheDutchDevil/toxicity-detection-bot@24daca3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_KEY: '6b075e93-2cea-46bd-af94-c5185b3a1a4e'